kind: pipeline
type: docker
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: build
  image: ubuntu
  commands:
  - apt update
  - apt install -y make pandoc tree docker
  - make
- name: docker
  image: plugins/docker
  settings:
    registry: ghcr.io
    username: uakci
    password:
      from_secret: registry_pass
    repo: ghcr.io/uakci/ithkuil.place
    tags: latest
  when:
    repo:
    - uakci/ithkuil.place
- name: webhook
  image: plugins/webhook
  settings:
    urls:
      from_secret: webhook_url
  when:
    repo:
    - uakci/ithkuil.place
