#!/bin/bash

# Please make sure that all URLs in MIRRORS end in a slash.

export MIRRORS=(
  "2011-en:0:http://ithkuil.net/"
  "2004-ru:0:http://ithkuil-russian.narod.ru/"
  # the ‘id_’ postfixed to the timestamp instructs Wayback Machine not to add
  # its toolbar onto the webpage
  "2004-en:5:https://web.archive.org/web/20090311041719id_/http://ithkuil.net:80/"
  # @uakci: I’m putting these ones on hold. They look fine on their own, are
  # accessible, and I don’t mean to infringe on the authors’ rights (or
  # hurt their pride).
  # "2011-ru:0:https://ithkuil-rus.github.io/"
  # "eloerktha:0:https://eloertkha.svbtle.com/"
)
